require('vstudio')

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
    premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
    premake.w('<VcpkgTriplet>x64-windows</VcpkgTriplet>')
    premake.w('<VcpkgEnabled>true</VcpkgEnabled>')
    premake.w('<VcpkgEnableManifest>true</VcpkgEnableManifest>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
    return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
    local calls = base(prj)
    table.insertafter(calls, vs.globals, vcpkg)
    return calls
end)

workspace "Lullaby Engine"
   architecture "x64"
   configurations { "Debug", "Release", "Dist" }
   startproject "LullabyEditor"
   
   flags
	{
		"MultiProcessorCompile"
	}

   -- Workspace-wide build options for MSVC
   filter "system:windows"
      buildoptions { "/EHsc", "/Zc:preprocessor", "/Zc:__cplusplus" }

OutputDir = "%{cfg.system}-%{cfg.architecture}/%{cfg.buildcfg}"

VULKAN_SDK = os.getenv("VULKAN_SDK")

include "Dependencies/Dependencies.lua"
include "LullabyCore/Build-Core.lua"
include "LullabyEditor/Build-Editor.lua"